#
# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

[workspace]
members = [".", "./macros"]

[package]
name = "quilkin"
version = "0.2.0-dev"
authors = ["Mark Mandel <markmandel@google.com>", "Ifeanyi Ubah <ifeanyi.ubah@embark-studios.com>"]
license = "Apache-2.0"
description = "Quilkin is a non-transparent UDP proxy specifically designed for use with large scale multiplayer dedicated game server deployments, to ensure security, access control, telemetry data, metrics and more."
homepage = "https://github.com/googleforgames/quilkin"
repository = "https://github.com/googleforgames/quilkin"
readme = "README.md"
keywords = ["proxy", "game-server", "game-development", "networking", "multiplayer"]
categories = ["game-development", "network-programming"]
edition = "2018"
exclude = ["docs", "build", "examples", "image"]

[[bench]]
name = "throughput"
harness = false
test = true

[dependencies]
# Local
quilkin-macros = { version = "0.2.0-dev", path = "./macros" }

# Crates.io
backoff = "0.3"
base64 = "0.13"
base64-serde = "0.6"
bytes = "1.0.1"
clap = "2.33.0"
either = "1.6.1"
humantime-serde = "1.0.0"
hyper = "0.14.2"
num_cpus = "1.13.0"
parking_lot = "0.11.0"
prometheus = { version = "0.12", default-features = false }
prost = "0.8.0"
prost-types = "0.8.0"
rand = "0.8"
rhai = { version = "1.0.1", features = [ "sync", "unchecked", "no_float", "no_module", ]}
rlua = "0.17.0"
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.60"
serde_yaml = "0.8.11"
slog = "2.7.0"
slog-async = "2.6.0"
slog-json = "2.3.0"
slog-term = "2.5.0"
snap = "1.0.3"
tokio = { version = "1.8.2", features = ["rt-multi-thread", "signal", "test-util", "parking_lot"] }
tokio-stream = "0.1.2"
tonic = "0.5.0"
uuid = {version = "0.8.1", default-features = false, features = ["v4"]}
thiserror = "1.0.25"

[dev-dependencies]
reqwest = "0.11.0"
regex = "1.3.9"
criterion = { version = "0.3", features = ["html_reports"] }
once_cell = "1.8.0"

[build-dependencies]
tonic-build = { version = "0.5.1", default_features = false, features = ["transport", "prost"] }
prost-build = "0.8.0"
